### ISSUE TITLE
Accessibility Problems

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#111]
- [x] Need a way to get to the "normal page" of a demo (Probably Debug View) https://twitter.com/stommepoes/status/701814411825192961 (see next checklist item... seems like this is a no-js issue, which now includes a link to Debug View)
- [x] `<noscript>` modal should also offer link to Full or Debug view (now does [this](http://d.pr/i/1lfTd/4J0RHx67))
- [ ] Tabbing around the page ([see below](https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/111#issuecomment-188382100))
- [ ] Focus on modals ([see below](https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/111#issuecomment-188382906))
- [x] Header outline
  - As [reported by](https://github.com/CodePen/redesign/issues/300) @MichielBijl:
    > Pen's title is a h1, which is good. Description title is a h4, where did h2 and h3 go? Same thing with the tags and comments titles.
- [ ] Test Embeds
  - See [these results](http://a11ynot.com/codepenEmbed.html)
- [ ] Keyboard navigation in search ([see below](https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/111#issuecomment-188384059))

**Comment by AmeliaBR** [comment]
The largest issue is that there is no keyboard-only way to "escape" the code editing panes. And the HTML editor pane get keyboard focus by default. Tab keypresses are just typing, not navigation, so there's no way to get to the other editor panes or the preview iframe.   Screen reader users can use landmarks (jump to header or nav) if supported by their software, (and from there to the Full/Debug view) but that's not really optimized, either.

**Comment by StommePoes** [comment]
Heck, for plain-keyboard users, a set of skip links (to each pane and then the content underneath) would do a lot with a small change code-wise.

**Comment by chriscoyier** [comment]
## Tabbing / Escape Key

Tabbing around the page is a HUGE thing for keyboard only users (blind or otherwise). Because when you're IN an editor on CodePen, hitting the tab key inserts 2 spaces rather than moving to another area. That's how it would work with any textarea. Even JSBin has a textarea mode for accessibility, but they handle it by eating the tab key. 

I was talking to Derek Featherstone, an accessibility dude, and he thought about this and had a great idea. The escape key should un-focus the editor. Like have the editor as the selected element still, but not be in editing mode. That way you could tab over to the next editor and enter it if you wanted. 

The real trick though, is saving the position within th editor. So you can escape out of it, but then RETURN back into it and be right where you were.

The escape key will have a bunch of duties then:

- Closing modals
- Removing search results
- Leaving editors

---

Video explanation by me: https://dl.dropboxusercontent.com/u/460771/better%20tabbing.mp4

---

Another possible accessibility feature is just turning off CodeMirror entirely (JS Bin takes this route). Pretty complicated though, as we'd have a whole new system of watching the textarea for changes and still doing the rest of the stuff.

**Comment by chriscoyier** [comment]
## Modal Focus

<img width="456" alt="screen shot 2015-10-28 at 3 03 26 pm" src="https://cloud.githubusercontent.com/assets/69156/10804526/1e4ab386-7d85-11e5-981a-e45ffc5184f1.png">

**Comment by chriscoyier** [comment]
Comment about keyboard navigation in search, submitted by email [Internal 4031]

>When you search codepen by clicking the search icon, it automatically sets focus on the search field.
>
>This is great, because thats exactly where i want to be.
>
>From then on however, it's a real pain, because keyboard nav is then broken, since i cant scroll using the arrow keys or page up/down keys....
>
>Can i suggest that the page checks to see if there is anything in the search field, and only sets focus if the field is empty? This way a new search always focuses, but an ongoing pagination of a search doesn't, and leaves the keyboard nav intact!

**Comment by StommePoes** [comment]
Yeah scrolling with arrows is a HUGE thing, I'm currently yelling about it with ARIA tab panels :)  PgUp/pgDn is always way too disorienting for me visually. Sometimes this can be fixed simply by having a safe place to put focus and THEN we can scroll...

For ESC + modals, on websites I tend to set the event listener when the modal is created/shown, and bind ESC there, and remove the event listener when the modal is closed/destroyed (because yes often ESC listeners are sitting elsewhere on the same page waiting to do stuff). Since your keyboard should be trapped within a modal, putting the ESC listener on the modal itself rather than document etc ought to work well.

For returning to the editor, I wonder if the similar trick could be used as when we open a modal: we save the triggering target as temp variable LastFocussedThingie and set .focus() on it when we close our modal (no matter how we do it), so I suppose a slightly more sophisticated version for the editor could do the same (I don't know how you remember cursor place).

Re blind vs nonblind keyboarders: if you have a screen reader (which we'll assume most blind users may have while most sighted, even if poorly, users will not) there are non-tab navigation methods available AND usually two modes, one where your keystrokes will move a virtual cursor (or real cursor if you turned on caret nav in for example Firefox) around, and one where you know your keystrokes will do typing (focus mode), and you can configure how this is presented to you but so usually obvious that you're now in an editable-thingie. Without a screen reader, as I start tabbing and I end up in something like the editor, I have to notice my tabs are changing code first, backtrack, then figure out what to do, visually. 
So I'm just saying there is a difference in what people experience depending on what they're using.

Also, I would probably need a hint to know Esc would work to get out of the editor. For popups and modals and stuff, I expect it as it's common, but I actually had never figured out for example how to get through JSbins-- I've always shift-tabbed from the bottom up since that usually gets me to the rendered part first. Maybe that was Fiddle, can't remember.

My unsolicited advice is to try easy simple stuff first (skip links, ESC for the modals etc) and see how that goes before trying the complicated stuff that has to keep track of states.

Also, yeah Derek's a good one to talk to. ++

**Comment by RichCaloggero** [comment]
One thing which no one has mentioned on this thread is the fact that as a screen reader user, when your focus is in the editor, you cannot actually read / interact / perceive any text therein. This is a code mirror issue from what I have observed; I downloaded and played with code mirror separately and it behaved exactly the same.  

Maybe someone more versed in the inner workings of the editor could chime in here and comment. WHat are they doing that is preventing text from actually being read in the editor?  

There was one comment which did mention that jsbin allowed one to edit via a textarea; this seems to be effective, but as was already mentioned, probably won't happen because of complexity of implementation.

-- Rich

**Comment by chriscoyier** [comment]
Note on how JSBin toggles to `<textarea>`

![img](http://d.pr/i/1i3U7/hIBxUSwC+)

**Comment by RichCaloggero** [comment]
Sorry, was there supposed to be a response here? All I see is an image with 
no altText. If the response is a screenshot or image of some kind, its not 
accessible and I can't read it!
-- Rich


-----Original Message-----

**Comment by AmeliaBR** [comment]
Whoops, looks like GitHub needs to work on its accessibility game, too.  No reminder to add alt when you add an image, it just grabs the file name or uses "image" if you paste from clipboard.  You need to manually edit the generated markdown notation (alt text inside the brackets, like `![alt text](image-url)`).

Demo:  
![Deckfailcat, a cartoon of the GitHub octocat mascot, teary-eyed and holding a slide saying #DeckFail.  Which seems close enough for the circumstances.](https://octodex.github.com/images/deckfailcat.png)

@chriscoyier posted a screenshot from JSBin in text-editor mode, with an arrow pointing to the checkbox that turns it on.

**Comment by RichCaloggero** [comment]
Ah thanx, very helpful;

-- R


-----Original Message-----

**Comment by dvalle910** [comment]
Anyone have help for when I try to make a <well> show depth, but it doesn't? Does anyone else have this same problem?

**Comment by MichielBijl** [comment]
@dvalle910 what is the question?

**Comment by mariemosley** [comment]
We're closing this repo and moving bugs and other known issues to our new [Known Issues trello board] (https://trello.com/c/gLCxXTOl/5-accessibility). We've also opened several internal issues addressing the accessibility problems mentioned in this thread.

I want to thank everyone who participated in this thread for taking the time to comment and share your suggestions. If you have feedback you'd like to share or have any questions please get in touch with us by email, support@codepen.io
